#!/bin/bash

if [ -z "${FINALEMACROS_DIR}" ]; then
	FINALEMACROS_DIR="/Applications/Hotkey Grid.app/Contents/Resources/scripts/finale-macros"
fi

if [ ! -d "$FINALEMACROS_DIR" ]; then
	echo "Hotkey Grid (Joseph's version) doesn't exist."
	exit
fi

FINALEMACROSZIPFILE="${FINALEMACROS_DIR}/master.zip"

echo "downloading current .zip of finale-macros from Github..."
cd "$FINALEMACROS_DIR" && curl -LO https://github.com/jsphweid/finale-macros/archive/master.zip

echo "unzipping archive..."
unzip -qo "${FINALEMACROSZIPFILE}" -d "${FINALEMACROS_DIR}"

echo "moving files from temp unzipped folder into main folder"
cp -r "${FINALEMACROS_DIR}/finale-macros-master/." "${FINALEMACROS_DIR}"

echo "removing temp unzipped folder"
rm -rf "${FINALEMACROS_DIR}/finale-macros-master"

echo "removing original downloaded .zip"
rm -rf "${FINALEMACROSZIPFILE}"

echo "end"